### ISSUE TITLE
运行demo

### ISSUE THREAD

**Issue by youngyoung611** [Holmeyoung/crnn-pytorch#13]
运行demo时输出全是乱码?

**Comment by Holmeyoung** [comment]
嗨，demo是我训练的中文字符集，会不会是您的终端不支持中文字符呢～

**Comment by youngyoung611** [comment]
> 嗨，demo是我训练的中文字符集，会不会是您的终端不支持中文字符呢～

我是用的pycharm运行的，请问怎么判断终端能不能支持中文字符呢?

**Comment by Holmeyoung** [comment]
抱歉才看见，我不用pycharm，但是网上搜了一下，你看看这样设置可以不
`Pycharm ---->  File ----> Default setting ------> Editor -------> File Encodings -------> 设置成UTF-8`
