### ISSUE TITLE
create_dataset.py

### ISSUE THREAD

**Issue by niddal-imam** [Holmeyoung/crnn-pytorch#15]
I am tying to use MJSynth 90 K, which continues millions of images. However, when I try to create dataset, only about 500K images can created. Is there a way of increasing this number?

**Comment by Holmeyoung** [comment]
Hi, the program is designed to create dataset of `999999999` max.
```python
imageKey = 'image-%09d' % cnt
labelKey = 'label-%09d' % cnt
```
And the lmdb file can be `1 TB` size.
```python
env = lmdb.open(outputPath, map_size=1099511627776)
```
So, i guess maybe you run out of the disk space.

Use `df path/to/your/file/folder` to see the mount location.
![image](https://user-images.githubusercontent.com/18281399/60145112-93914c00-97f7-11e9-9517-6aa778d52e95.png)

Use `df -h` to see the details.
![image](https://user-images.githubusercontent.com/18281399/60145132-aad03980-97f7-11e9-9f63-ff60679d6d1a.png)

If there are still problems, we can solve it together. Good luck~

**Comment by niddal-imam** [comment]
I checked the disk space. 
![image](https://user-images.githubusercontent.com/47844140/60151596-35ec0800-97d5-11e9-8ce0-8c7bf6b16119.png)

I am still getting this error:

Written 620000 / 802734
Traceback (most recent call last):
  File "tool/create_dataset.py", line 125, in <module>
    createDataset(args.out, image_path_list, label_list)
  File "tool/create_dataset.py", line 62, in createDataset
    if not checkImageIsValid(imageBin):
  File "tool/create_dataset.py", line 14, in checkImageIsValid
    imgH, imgW = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Holmeyoung** [comment]
Hi, i have fixed it.
![image](https://user-images.githubusercontent.com/18281399/60155455-c13cbc00-981c-11e9-9674-d5f37979e2c1.png)

By the way, you can print the image path while the program throws the error. Maybe it's a `txt, json...etc` or any other `not image file` exists in your folder.

**Comment by niddal-imam** [comment]
Perfect. 

Many thanks
