### ISSUE TITLE
input to train.py 

### ISSUE THREAD

**Issue by SreenijaK** [Holmeyoung/crnn-pytorch#17]
I want to train with my own dataset. First I used the create_dataset.py and it created two files- data.mdb and lock.mdb.
Now i gave the same path of data.mdb to train and validate. If this is not right How do i split to train and validate.

And when i run train.py, I get the following error

File "train.py", line 60, in 
train_dataset = dataset.lmdbDataset(root=opt.trainRoot)
File "/home/ramu_yarru/ctpn/crnn.pytorch/dataset.py", line 25, in init
meminit=False)
lmdb.Error: /home/ramu_yarru/ctpn/crnn_train/data/train/data.mdb: Not a directory

What exactly is the input to train.py ?

**Comment by niddal-imam** [comment]
You need to create two files train.txt and val.txt and then run create_dataset.py for both files. This will create train with two data.mdb and val with two data.mdb.

**Comment by SreenijaK** [comment]
Thanks so my input to the train file will the dataset folder ? 
python train.py --trainroot path/to/train/dataset --valroot path/to/val/dataset.

If we are giveing the folder as input where do we use the .mdb files?

**Comment by niddal-imam** [comment]
Yes, trainroot is the path to train folder which contains two data.mdb files, and valroot is the path to val folder. train.py will read the data.mdb files.

**Comment by SreenijaK** [comment]
thank you,
So I've created two folders and train and valid. i've changed the alphabets too , and when i try to train i get the following error .

  File "train.py", line 178, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 155, in trainBatch
    t, l = converter.encode(cpu_texts)
  File "/home/ramu_yarru/ctpn/crnn-pytorch/utils.py", line 61, in encode
    index = self.dict[char]
KeyError: ' '

**Comment by SreenijaK** [comment]
i've created two folders train and validate. when i run i get this error RuntimeError: Tensor for argument #2 'targets' is on CPU, but expected it to be on GPU (while checking arguments for ctc_loss_gpu)

**Comment by SreenijaK** [comment]
from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/397#issuecomment-427750296 link i think error is because of line preds_size = Variable(torch.IntTensor([preds.size(0)] * batch_size)).
We might have to use torch.cuda module but torch.cuda doesnt have intTensor. Do you know how can i fix the same?

**Comment by Holmeyoung** [comment]
Hi, can you try to run the code in `python3.6`

**Comment by SreenijaK** [comment]
i'm using 3.5.3, should i upgrade to 3.6?

**Comment by Holmeyoung** [comment]
Hi, you are using 3.5, but why your pytorch in installed in 2.7
```bash
File "/home/ramu_yarru/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in call
```

**Comment by Holmeyoung** [comment]
Are you using anaconda? If so, you should use `pip install` but not `sudo pip install`. Maybe it’s the issue.

**Comment by SreenijaK** [comment]
when i run with python3 i get the same error:
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 163, in trainBatch
    cost = criterion(preds, text, preds_size, length) / batch_size
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 1332, in forward
    self.zero_infinity)
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1813, in ctc_loss
    zero_infinity)
RuntimeError: Tensor for argument #2 'targets' is on CPU, but expected it to be on GPU (while checking arguments for ctc_loss_gpu)

**Comment by SreenijaK** [comment]
but when i make cuda false the code runs but is too slow. 

And also when i change the height to 64 and width to 900 it throws an error, what do i do to change my height to 64?
And If i want to train with more than 26 length, what changes should i make

**Comment by Holmeyoung** [comment]
Hi, can you try to replace the `int` with `long` as said in
https://discuss.pytorch.org/t/ctc-loss-function-not-working-with-cuda-when-using-torch-int32/30152

**Comment by Holmeyoung** [comment]
When you change the height to 64 and width to 900, what's the error output.
And if you want to change length 26, you need to change the net structure in `crnn.py`. The T length in lstm.

**Comment by SreenijaK** [comment]
when i change it to long i get this error:
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 161, in trainBatch
    preds_size = Variable(torch.long([preds.size(0)] * batch_size)).cuda()
TypeError: 'torch.dtype' object is not callable

when i change it to torch.LongTensor. i get following error:
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 163, in trainBatch
    cost = criterion(preds, text, preds_size, length) / batch_size
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 1332, in forward
    self.zero_infinity)
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1813, in ctc_loss
    zero_infinity)
RuntimeError: Tensor for argument #2 'targets' is on CPU, but expected it to be on GPU (while checking arguments for ctc_loss_gpu)
based on this https://pytorch.org/docs/stable/tensors.html reference i changes to torch.cuda.LongTensor.  i get following error.
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 163, in trainBatch
    cost = criterion(preds, text, preds_size, length) / batch_size
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 1332, in forward
    self.zero_infinity)
  File "/home/ramu_yarru/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1813, in ctc_loss
    zero_infinity)
RuntimeError: Tensor for argument #2 'targets' is on CPU, but expected it to be on GPU (while checking arguments for ctc_loss_gpu

**Comment by SreenijaK** [comment]
hi I changed to torch.cuda.LongTensor in all the places and the code seems to work fine. thank you so much.

**Comment by SreenijaK** [comment]
When i change the height to 64 and width to 900 i get this error:
AssertionError: the height of conv must be 1

**Comment by Holmeyoung** [comment]
OK, it's the conv in `crnn.py`
```python
    def forward(self, input):
        # conv features
        conv = self.cnn(input)
        b, c, h, w = conv.size()
        assert h == 1, "the height of conv must be 1"
        conv = conv.squeeze(2)
        conv = conv.permute(2, 0, 1)  # [w, b, c]

        # rnn features
        output = self.rnn(conv)
```
If you want to change, you need to change the input shape into `rnn` from [w, b, c] to [length, b, c*height].
The length and height is not the origin length and height, but is the length and height after conv.

**Comment by SreenijaK** [comment]
ok so my images can be of any height and length right? they all dont have to be of same height and width and can be variable?

**Comment by Holmeyoung** [comment]
Yes, the training images will be reshaped to the same.

**Comment by SreenijaK** [comment]
and if i want my max length to predict to be 64 where exactly do i change?

**Comment by Holmeyoung** [comment]
Just change params.imgW to 254.
Also， change `train.py` to
```python
test_dataset = dataset.lmdbDataset(root=args.valroot, transform=dataset.resizeNormalize((params.imgW, params.imgH)))
```

**Comment by SreenijaK** [comment]
what is the reason we are making it to 254?

**Comment by SreenijaK** [comment]
> When you change the height to 64 and width to 900, what's the error output.
> And if you want to change length 26, you need to change the net structure in `crnn.py`. The T length in lstm.
Where do i change for more than 26 characters in crnn.py

**Comment by Holmeyoung** [comment]
You need to calculate it. After conv and pool what's the image width. The image width will be T length in rnn.

**Comment by SreenijaK** [comment]
sorry for asking too many questions but whats the calculation that you did to get 254

**Comment by Holmeyoung** [comment]
It doesn’t matter. 
For example, a 6*6 image, after  3*3 con kernel, it will be 6-3+1=4. So it’s 4*4. And after 2*2 max pool, it will be 4/2=2. So it’s 2*2.

**Comment by SreenijaK** [comment]
thank you i understand your calculations but i still am confused on how did we end up at 254

**Comment by Holmeyoung** [comment]
#### Changed the net structure.
```python
        self.conv_0 = convRelu(conv_0, 0)
        self.pool_0 = nn.MaxPool2d(2, 2)
        self.conv_1 = convRelu(conv_1, 1)
        self.pool_1 = nn.MaxPool2d(2, 2)
        self.conv_2 = convRelu(conv_2, 2, True)
        self.conv_3 = convRelu(conv_3, 3)
        self.pool_2 = nn.MaxPool2d((2, 2), (2, 1), (0, 1))
        self.conv_4 = convRelu(conv_4, 4, True)
        self.conv_5 = convRelu(conv_5, 5)
        self.pool_3 = nn.MaxPool2d((2, 2), (2, 1), (0, 1))
        self.conv_6 = convRelu(conv_6, 6, True)

        self.rnn_0 = BidirectionalLSTM(512, nh, nh)
        self.rnn_1 = BidirectionalLSTM(nh, nh, nclass)
```

#### Print the data shape
```bash
        print ('\n----------------------')
        print (input.shape)
        # conv features
        x = self.conv_0(input)
        print ('conv_0:', x.shape)
        x = self.pool_0(x)
        print ('pool_0:', x.shape)
        x = self.conv_1(x)
        print ('conv_1:', x.shape)
        x = self.pool_1(x)
        print ('pool_1:', x.shape)
        x = self.conv_2(x)
        print ('conv_2:', x.shape)
        x = self.conv_3(x)
        print ('conv_3:', x.shape)
        x = self.pool_2(x)
        print ('pool_2:', x.shape)
        x = self.conv_4(x)
        print ('conv_4:', x.shape)
        x = self.conv_5(x)
        print ('conv_5:', x.shape)
        x = self.pool_3(x)
        print ('pool_3:', x.shape)
        x = self.conv_6(x)

        print ('conv_6:', x.shape)
        b, c, h, w = x.size()
        assert h == 1, "the height of conv must be 1"
        conv = x.squeeze(2)
        conv = conv.permute(2, 0, 1)  # [w, b, c]

        # rnn features
        rnn = self.rnn_0(conv)
        print ('lstm_0:', rnn.shape)
        output = self.rnn_1(rnn)
        print ('lstm_1:', output.shape)
```

#### Result
```bash
----------------------
torch.Size([64, 1, 32, 254])
conv_0: torch.Size([64, 64, 32, 254])
pool_0: torch.Size([64, 64, 16, 127])
conv_1: torch.Size([64, 128, 16, 127])
pool_1: torch.Size([64, 128, 8, 63])
conv_2: torch.Size([64, 256, 8, 63])
conv_3: torch.Size([64, 256, 8, 63])
pool_2: torch.Size([64, 256, 4, 64])
conv_4: torch.Size([64, 512, 4, 64])
conv_5: torch.Size([64, 512, 4, 64])
pool_3: torch.Size([64, 512, 2, 65])
conv_6: torch.Size([64, 512, 1, 64])
lstm_0: torch.Size([64, 64, 256])
lstm_1: torch.Size([64, 64, 8])
```

**Comment by Holmeyoung** [comment]
Due to the data is not divisible sometime, maybe there are other results exitst.

**Comment by SreenijaK** [comment]
got it thank you. 
when i ran train.py i got the following error.
CRNN(
  (cnn): Sequential(
    (conv0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu0): ReLU(inplace)
    (pooling0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu1): ReLU(inplace)
    (pooling1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (conv2): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu2): ReLU(inplace)
    (conv3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3): ReLU(inplace)
    (pooling2): MaxPool2d(kernel_size=(2, 2), stride=(2, 1), padding=(0, 1), dilation=1, ceil_mode=False)
    (conv4): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu4): ReLU(inplace)
    (conv5): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5): ReLU(inplace)
    (pooling3): MaxPool2d(kernel_size=(2, 2), stride=(2, 1), padding=(0, 1), dilation=1, ceil_mode=False)
    (conv6): Conv2d(512, 512, kernel_size=(2, 2), stride=(1, 1))
    (batchnorm6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu6): ReLU(inplace)
  )
  (rnn): Sequential(
    (0): BidirectionalLSTM(
      (rnn): LSTM(512, 256, bidirectional=True)
      (embedding): Linear(in_features=512, out_features=256, bias=True)
    )
    (1): BidirectionalLSTM(
      (rnn): LSTM(256, 256, bidirectional=True)
      (embedding): Linear(in_features=512, out_features=131, bias=True)
    )
  )
)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f959be13158>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

however i have thses in my expr:
netCRNN_0_1.pth  netCRNN_0_2.pth

**Comment by SreenijaK** [comment]
Ok got it thank you.
