### ISSUE TITLE
训练问题，accuray一直为0

### ISSUE THREAD

**Issue by mayday0208** [Holmeyoung/crnn-pytorch#22]
![crnn](https://user-images.githubusercontent.com/53076890/61518556-69206080-aa3c-11e9-9129-e550adb1b3fc.jpg)

**Comment by Holmeyoung** [comment]
嗨，
首先，看loss，如果loss在降低，咱们就耐心等一等，准确率会上来的
如果loss一直没怎么变，那就需要增加训练数据了。
