### ISSUE TITLE
Create illegal symbol in File mode

### ISSUE THREAD

**Issue by thaihaquang** [Holmeyoung/crnn-pytorch#24]
As you said, there are limitations (illegal character) when you use Folder mode. But in File mode, these characters are also unallowed in Filename, So how can File mode solve this problem?'
Thank you.

**Comment by Holmeyoung** [comment]
Hi, make the file like
```
absolute/path/to/image/hi_0.jpg
\/***
absolute/path/to/image/name_1.jpg
\\\\<>|
```
and so on

**Comment by thaihaquang** [comment]
> Hi, make the file like
> 
> ```
> absolute/path/to/image/hi_0.jpg
> \/***
> absolute/path/to/image/name_1.jpg
> \\\\<>|
> ```
> 
> and so on

Thank you. So the filename is arbitrary. The label will be read from the line below Filename (2nd line, 4th line, ...). Is it right?

**Comment by Holmeyoung** [comment]
YES！
