### ISSUE TITLE
assertion error arise

### ISSUE THREAD

**Issue by monica061** [Holmeyoung/crnn-pytorch#37]
Hii sir, have created lmdb dataset using txt file of train as well as val, and i got data.mdb and lock .mdb of both the files but there is arising an assertion error while in the line during assert train , please help me out in this.

**Comment by Holmeyoung** [comment]
Hi, can you post the detail error log here~~

**Comment by monica061** [comment]
Hii,

Thankyou for your reply but the problem is been solved now .

Monica
