### ISSUE TITLE
I tried to reproduce your code, but failed, cost stuck at 7.0

### ISSUE THREAD

**Issue by jaysimon** [Holmeyoung/crnn-pytorch#40]
I tried to reproduce your code, but failed, cost stuck at 7.0. Code is here: 
https://github.com/jaysimon/crnn-houwei

By using SyntheticChineseStringDataset, your code runs well, cost decrease from 8.0 to 2.0 or less. Your model predicts well.
While I tried to build the model by myself, cost stuck at 7.0.
Any idea or advice?
Thank you very much.

**Comment by jaysimon** [comment]
I tried almost everything in your repository: reshape to (32, 100), normalized to (-1.0, 1.0), same network, same ctcloss, same lmdb data, same net weight init.
But failed, I dont know why.

**Comment by Holmeyoung** [comment]
Hi, what did  you change in the net, I see no model file here
https://github.com/jaysimon/crnn-houwei/tree/master/model

Maybe you can clone it first and change it little by little, see what will happen~~~

**Comment by jaysimon** [comment]
> Hi, what did you change in the net, I see no model file here
> https://github.com/jaysimon/crnn-houwei/tree/master/model
> 
> Maybe you can clone it first and change it little by little, see what will happen~~~

model  is in the train.py.
I will check it carefully.
Thanks a lot!
