### ISSUE TITLE
How to create train and val data?

### ISSUE THREAD

**Issue by NavneetSajwan** [Holmeyoung/crnn-pytorch#45]

**Comment by ghost** [comment]
http://www.robots.ox.ac.uk/~vgg/data/text/#sec-synth

**Comment by NavneetSajwan** [comment]
> http://www.robots.ox.ac.uk/~vgg/data/text/#sec-synth

Thanks for the response. I've got the data. Do I have to execute STEP 2 both for training and Validation data? What exactly is the purpose of step 2?

**Comment by ghost** [comment]
STEP 2 aims to convert the images and label to lmdb format. all images and labels are stored together in one lmdb file. lmdb format is more efficient to read during training.

**Comment by wfdubowen** [comment]
https://github.com/Sanster/text_renderer
