### ISSUE TITLE
数据集尺寸问题

### ISSUE THREAD

**Issue by VixeruntR** [Holmeyoung/crnn-pytorch#51]
请问您训练的图像尺寸都是一样的吗？如果我的数据集图像都不一样尺寸，是否要保持比例先行padding并resize到一样（32*100）？

**Comment by Holmeyoung** [comment]
不用，丢进去就行了

**Comment by VixeruntR** [comment]
> 
> 
> 不用，丢进去就行了

比如有的图片只有1个字，有个有10个字，而且高度也都不是32，比如(10, 60)和（20, 20），那么都resize到（100, 32）的话，字体不是都变形了嘛？感谢您的解答。

**Comment by Holmeyoung** [comment]
如果你数据集的大部分图片宽高比大概在100:32，那直接丢进去就行

如果你数据集的大部分图片宽高比大概在另一个集中的范围，那就设置`keep_ratio=True`, 这样会寻找宽高比最大的张图片做为base去resize

如果你的数据集中，图片宽高比差别太大，那可以考虑你说的办法，给它padding一下

**Comment by VixeruntR** [comment]
> 
> 
> 如果你数据集的大部分图片宽高比大概在100:32，那直接丢进去就行
> 
> 如果你数据集的大部分图片宽高比大概在另一个集中的范围，那就设置`keep_ratio=True`, 这样会寻找宽高比最大的张图片做为base去resize
> 
> 如果你的数据集中，图片宽高比差别太大，那可以考虑你说的办法，给它padding一下

好的，非常感谢您的解答！另外您自己训练的数据集是大概都在100*32这样子的么？

**Comment by Holmeyoung** [comment]
不是100*32的，但是我的数据集宽高比集中在另一个范围，我也没有设置`keep_ratio=True`，这样模型学出来的就是每个字都是胖乎乎的，或者瘦瘦的。

**Comment by VixeruntR** [comment]
明白了 谢谢解答！
