### ISSUE TITLE
Log_softmax issue

### ISSUE THREAD

**Issue by JustVugg** [Holmeyoung/crnn-pytorch#54]
What can you replace log_softmax with in the forward? I'm having trouble with the conversion.

**Comment by Holmeyoung** [comment]
You can just remove it.

**Comment by JustVugg** [comment]
In the meantime I tried you are right.Thank you very much.I wanted to take this opportunity to ask you if you have ever converted your model to ncnn.

**Comment by Holmeyoung** [comment]
Sorry, I did't ever convert the model to ncnn.

**Comment by JustVugg** [comment]
thank you for the help!
