### ISSUE TITLE
Training Problems

### ISSUE THREAD

**Issue by zhengyussss** [Holmeyoung/crnn-pytorch#68]
when i train by my own data , i meet this problem, i don't know how can i solve this problem,the problem as fellows:

/dataset.py", line 97, in __getitem__
    buf.write(imgbuf)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by zhengyussss** [comment]
i have fix this problem

**Comment by lcko1012** [comment]
same problem, can you tell me how to fix it :(
